name: uic_workshop_2026
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - pymupdf>=1.28
  - pillow
  - ipykernel
  - jupyter
  - requests
  - pip
  - pip:
      - ollama>=0.6
      - openai
